### PR TITLE
content is not always base64 encoded

### PR DESCRIPTION
**Pull request by jeff-cyft**

### CODE REVIEW

**Comment by danielfrg** [comment]
I thought this was fixed on: https://github.com/danielfrg/s3contents/pull/36
Do you have the latest version?

**Comment by jeff-cyft** [comment]
We had a box running 0.2.2 from February doing great.  Just set up a new box that got 0.1.8 from pip which appears to be the latest now?  We could no longer save files in Jupyter.  Noticed “content” passed to the write func was not actually base64 encoded (created an error in the base64 decode call).  Hence this proposal.

Not entirely sure what else may have changed.  I’ll check our Jupyter version etc. as soon as I can and report.  We have had great success with s3contents until now and want to help figure out what problem we hit in case others also encounter it.  Thanks!

**Comment by jeff-cyft** [comment]
It's Jupyter 5.2.1 on both boxes.

**Comment by danielfrg** [comment]
Got it. I'll try this later and report back. Thanks for the extra info.

**Comment by jeff-cyft** [comment]
@danielfrg Thanks for following up.  Snooping in the Jupyter native file i/o implementation of contents manager it looks like the file model includes a `format` key which indicates whether the contents are base64 encoded.  I modified this PR to handle the same way its handled in Jupyter.  Feel free to adapt to local standards for s3contents, etc.  But this approach seems to work in both `5.2.1` and `5.5.0`
https://github.com/jupyter/notebook/blob/master/notebook/services/contents/fileio.py#L325

**Comment by danielfrg** [comment]
Thanks for finding that out. I'll test later and release it.

**Comment by danielfrg** [comment]
Tested and it works fine. Merging now.

**Comment by jeff-cyft** [comment]
This release is immensely helpful.  Thank you @danielfrg

**Pull request merged**
