### PR TITLE
fixed: notebook upload that use the chunk

### PR DESCRIPTION
**Pull request by machero**
fixed the large ipynb file upload

### CODE REVIEW

**Comment by danielfrg** [comment]
Thanks for you contribution!

Do you know why is this required for large notebook files?

**Comment by machero** [comment]
seem like jupyter will split the large notebook files(1.5M+) to multiple chunks, the fuction  `_notebook_model_from_path `  use to load the notebook file model(save-->_save_large_file-->get-->_notebook_model_from_path)

**Comment by danielfrg** [comment]
Is this not needed anymore

**Comment by machero** [comment]
To be honest,This change is needed for us, but I am not certainly sure whether this change will affect the architecture or have same bad affect, so I closed it temporarily. If there are any problems, I hope you can point them out, i try to fixed them

**Comment by danielfrg** [comment]
If it's needed I want to merge it I just havent had time to test it and see if there are any issues. I havent changed that code in a while so I am not sure of any consequences.

Since test pass I might just merge it.

**Comment by machero** [comment]
Thanks, can you release a new version?

**Comment by danielfrg** [comment]
Yes, I will release one tomorrow

**Comment by danielfrg** [comment]
I just uploaded a new version

**Pull request merged**
