### PR TITLE
Added configuration to be able to enable S3 SSE-KMS using a CMK.

### PR DESCRIPTION
**Pull request by hocanint-amzn**
This code change adds the ability to add S3 SSE-KMS key for encryption. The code changes are relatively simple. Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by danielfrg** [comment]
Thanks for the PR!
not sure whats up with travis CI not being green but looks like tests passed just fine so merging.

**Comment by danielfrg** [comment]
I can try to release later today or in the week to pypi if you need it there

**Comment by hocanint-amzn** [comment]
Hello Daniel, thanks for merging this. I have tested these changes locally, but if you can just do a quick test just to make sure nothing broke as this is my first PR, I would appreciate it.

**Comment by danielfrg** [comment]
I will, thank you so much for your contribution!

**Pull request merged**
