### PR TITLE
Release 0.6.0

### PR DESCRIPTION
**Pull request by ericdill**
Will merge once CI passes. Then will upload to pypi and cut a conda-forge release

### CODE REVIEW

**Comment by ericdill** [comment]
Why is this failing....

**Comment by ericdill** [comment]
@danielfrg should we be getting an access denied on minio? 
Screen Shot 2020-09-14 at 7 41 04 AM

**Comment by ericdill** [comment]
ok i can at least replicate these errors locally when I use pip to install the dependencies

**Comment by danielfrg** [comment]
> @danielfrg should we be getting an access denied on minio?

Yes, I think thats fine because its not passing the credentials, its just to test its alive.

**Comment by ericdill** [comment]
ok looks like _some_ kind of change in s3fs from 0.5.0 -> 0.5.1 breaks a couple of the tests in here. any idea what could have caused that? cc @martindurant for any support he can maybe lend here

**Comment by martindurant** [comment]
Perhaps because exceptions now come from aiohttp rather than requests?

**Comment by martindurant** [comment]
Sorry, both http and s3fs - same goes for botocore -> aiobotocore

**Comment by ericdill** [comment]
woo tests pass with s3fs 0.5.0. @danielfrg think this looks ok? If so i'll push the new tag and release to pypi and conda-forge. Updating s3fs to 0.5.1 is something that we can deal with in a subsequent release as time permits

**Comment by ericdill** [comment]
thanks @martindurant :)

**Comment by danielfrg** [comment]
Yes, lgtm to pin it. We have had to add and remove that pin like 4 times now lol :D

**Pull request merged**
