### PR TITLE
Dev env update and docs for local directories

### PR DESCRIPTION
**Pull request by danielfrg**

### CODE REVIEW

**Comment by rgbkrk** [comment]
What else do you see left for the next release?

**Comment by danielfrg** [comment]
Nothing else, if you need it I can make a new dot release this weekend.

**Comment by rgbkrk** [comment]
I'd love that. Thanks Daniel!

I'm likely going to use bits of this underneath a different contents manager to help transition us off our current storage (S3 only as archival, immutable artifacts for scheduling, "published" copies).

**Comment by danielfrg** [comment]
I just uploaded `0.1.11` to pypi. Let me know any issues.

**Pull request merged**
